---
title: "RiceAtlas - Questions and proposals for processing"
output:
  html_document:
    highlight: pygments
    theme: spacelab
    toc: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sprawl)
library(ggspatial)
library(ggplot2)
```

## Introduction

This document briefly illustrate the results of exploratory analysis conducted
using the PhnoRice algorithm to map rice area and estimate some agro-practices
indicator (number of rie seasons, Sowing and harvesting dates), starting from time 
series of MODIS 250m images

## Methods

The PhenoRice algorithm was applied to the 
   
2. What is "Maturity" ? 

  Maturity is the length of season. Not clear however what `MATURITYS` and
  `MATURITYE` are. Bhogendra will check. 

4. What is "seed_age" ? 

  Understood. Information is probably not relevant for our purposes

3. Where are the areas reported ? 

  Areas are on the right-most columns of RiceProduction. 

## Processing needed

To facilitate processing and comparison with PhenoRice results, it would be 
good if the dataset could be reshaped as follows: 

1. Remove all areas outside of the current PhenoRice analysis

2. Reshape the DB in a more "processing-friendly" format. I am thinking of something
   like this:
   
   - "Location" columns to be kept as is: `OBJECTID`, `ISO`, `COUNTRY`, `REGION`, `SUB_REGION`
   - "Location" columns to be added (if/where possible): `ISO_SUB`, corresponding to 
      the ISO code of the `SUB_REGION`
   -  Reshape the "data" columns to long format. What I'm thinking of is something on 
      these lines: 
      
      | OBJECTID | ISO  | ...  | nseas |season         | seas_cat   |pheno_var | start   | peak    | end | ricearea | totarea | rice_fc |riceprod |
      | :------: |:----:| :---:| :---: |:-------------:| :---------:|:--------:|:-------:|:-------:|:---:|:-------: |:-------:|:------:|:------:
      | 1        | VNM  | ...  | 2     | Winter-spring | first      | sow      |  10     | 20      | 30  | 2500     |  5000   | 0.5    | 2.1    |
      | 1        | VNM  | ...  | 2     | Summer        | second     | sow      |  100    | 110     | 120 | 1000     |  5000   | 0.5    | 1.1    |
      | 1        | VNM  | ...  | 2     | NA            | third      | sow      |  NA     | NA      | NA  | NA       |  5000   | 0.5    | NA     |
      | 1        | VNM  | ...  | 2     | Winter-spring | first      | harv     |  100    | 110     | 120 | 2500     |  5000   | 0.5    | 2.1    |
      | 1        | VNM  | ...  | 2     | Summer        | second     | harv     |  190    | 200     | 210 | 1000     |  5000   | 0.5    | 1.1    |
      | 1        | VNM  | ...  | 2     | NA            | third      | harv     |  NA     | NA      | NA  | NA       |  5000   | 0.5    | NA     |
      | 1        | VNM  | ...  | 2     | Winter-spring | first      | mat      |  60     | 70      | 80  | 2500     |  5000   | 0.5    | 2.1    |
      | 1        | VNM  | ...  | 2     | Summer        | second     | mat      |  150    | 160     | 170 | 1000     |  5000   | 0.5    | 1.1    |
      | 1        | VNM  | ...  | 2     | NA            | third      | mat      |  NA     | NA      | NA  | NA       |  5000   | 0.5    | NA     |
      | 2        | VNM  | ...  | 3     | Winter-spring | first      | sow      |  15     | 25      | 35  | 2500     |  5000   | 0.5    | 3      |
      | 2        | VNM  | ...  | 3     | Summer        | second     | sow      |  105    | 115     | 125 | 1000     |  5000   | 0.5    | 2      |
      | 2        | VNM  | ...  | 3     | Off           | third      | sow      |  200    | 205     | 210 | 500      |  5000   | 0.5    | 1      |
      
      
     
   -  This could be done either manually or in `R` by importing the dataset to a
      `sf` object and then using either functionalities from `reshape2::melt` or
      `tidyr::gather`. I'd suggest the second solution, which is less error-prone
      and recyclable/reproducible (and can be modified if we decide that we need 
      something more/less/different. The function could be added to `PhenoriceR`
      package. 
      
   -  For Bhogendra: Is it possible for you to work onthis re-sahping ? 
